window:
  padding:
    x: 8
    y: 8
background_opacity: 0.9
font:
  normal:
    family: Comic mono
  size: 12

colors:
  primary:
    background: "#000000"
    foreground: "#ffffff"
  normal:
    black:      "#111111"
    red:        "#cc0000"
    green:      "#00cc00"
    yellow:     "#cccc00"
    blue:       "#44bbff"
    magenta:    "#cc00cc"
    cyan:       "#00cccc"
    white:      "#cccccc"
  bright:
    black:      "#000000"
    red:        "#ff0000"
    green:      "#00ff00"
    yellow:     "#ffff00"
    blue:       "#66ccff"
    magenta:    "#ff00ff"
    cyan:       "#00ffff"
    white:      "#ffffff"
